### ISSUE TITLE
Synapse link to CMS subtypes call is not working

### ISSUE THREAD

**Issue by GMFranceschini** [Sage-Bionetworks/crcsc#63]
I would like to retrieve the CMS classification of TCGA-COAD that you described in this work https://www.nature.com/articles/nm.3967 . However, the link to the synpse repository seems to be broken. Is there any alternative to retrieve such data?
Best

**Comment by sgosline** [comment]
I recommend emailing the corresponding authors of the manuscript.

**Comment by aeolianine** [comment]
The data is still available. If you login to Synapse and search for "Colorectal Cancer Subtyping Consortium" you will find all datasets that the classification was trained on. The subtpying tool is here: https://github.com/Sage-Bionetworks/CMSclassifier. You can either run it on these datasets of even get the labels per sample from finalModel$y if you install the CMSclassifier package.

**Comment by GMFranceschini** [comment]
Thank you, I was completely missing the login part. Sorry for the inconvenience, closing the issue.
